### ISSUE TITLE
Produce a Release

### ISSUE THREAD

**Issue by elbrujohalcon** [marianoguerra/erlplorer#1]
Please produce a github release with an attached version of erlplorer so that people can just download the escript from there.
Thanks :)

**Comment by marianoguerra** [comment]
is there something particular about a "github release"? or I just put the build on a dist folder and create a tag? never used github for releases :)

**Comment by elbrujohalcon** [comment]
Follow the steps here
![marianoguerra_erlplorer_-_javascript](https://cloud.githubusercontent.com/assets/93657/12551956/2aa468da-c34d-11e5-815f-8a58e3085672.png)

**Comment by marianoguerra** [comment]
@elbrujohalcon thanks, here it is: https://github.com/marianoguerra/erlplorer/releases/tag/0.1 let me know if it's all ok.

**Comment by elbrujohalcon** [comment]
Excellent, thanks!
